local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/vshandy2/script/main/xheptcofficial%20gitbook.lua"))()
local test = Library.CreateLib("script", "Ocean")
local test = test:NewTab("script")
local test5 = test:NewSection("script")
test5:NewButton("Brookhaven 🏡 RP script", "", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/vshandy2/script/main/Brookhaven%20%F0%9F%8F%A1%20RP.lua"))()
end)
test5:NewButton("1x1x1x1 script", "", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/vshandy2/script/main/1x1x1x1.lua"))()
end)
test5:NewButton("explorer", "", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/vshandy2/script/main/explorer.lua"))()
end)
test5:NewButton("troll", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/vshandy2/script/main/troll.lua"))()
    end)
    